


---Users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

---Items table
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  available BOOLEAN NOT NULL,
  owner INTEGER NOT NULL,
  CONSTRAINT pk_item PRIMARY KEY (id)
);

----Booking table
CREATE TABLE IF NOT EXISTS booking (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date timestamp without time zone NOT NULL,
  end_date timestamp without time zone NOT NULL,
  item_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  status_name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_booking PRIMARY KEY (id),
  FOREIGN KEY (item_id) REFERENCES items (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
);

---Comment table
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(255) NOT NULL,
  created timestamp without time zone NOT NULL,
  item_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  CONSTRAINT pk_comments PRIMARY KEY (id),
  FOREIGN KEY (item_id) REFERENCES items (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
);